### ISSUE TITLE
Move react and react-dom to peerDependencies and devDependencies

### ISSUE THREAD

**Issue by sunnysingh** [whmountains/react-dial#2]
This just caused an issue in our app where we had two versions of React included after updating to React v15. The change to fix this is fairly simple, just move react and react-dom to peerDependencies and devDependencies. I can make a pull request if it's easier, but don't have the time currently.

See this for reference: http://stackoverflow.com/a/30454133

**Comment by whmountains** [comment]
I'd be happy to merge it if you make a pull request.

**Comment by whmountains** [comment]
Just curious, are you actually using this in production?

**Comment by vtaits** [comment]
Publish new version to npm, please.
Yes, i use this in production.

**Comment by whmountains** [comment]
I bumped the version and published to NPM.

Pardon my sluggish maintenance.  I never imagined that someone would use my humble module.
